### ISSUE TITLE
HPOneView Powershell Get-HPOVRemoteSupportSetting error

### ISSUE THREAD

**Issue by sbkurid** [HewlettPackard/POSH-HPEOneView#375]
### Expected Behavior
When executing Get-HPOVRemoteSupportSetting getting the below error mentioned in the Actual Behavior.

### Actual Behavior
```PowerShell
PS C:\Windows\system32> Get-HPOVServer -Name "name" | Get-HPOVRemoteSupportSetting
Get-HPOVRemoteSupportSetting : The term 'HPOneView.Appliance.RemoteSupportResourceException' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:38
+ Get-HPOVServer -Name "name" | Get-HPOVRemoteSupportSetting
+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HPOneView.Appli...sourceException:String) [Get-HPOVRemoteSupportSetting], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Get-HPOVRemoteSupportSetting
```

### Steps to reproduce

```PowerShell
VERBOSE: [GET-HPOVREMOTESUPPORTSETTING] Bound PS Parameters:
Key     Value
---     -----
Verbose True


VERBOSE: [GET-HPOVREMOTESUPPORTSETTING] Called from: <ScriptBlock>
VERBOSE: [GET-HPOVREMOTESUPPORTSETTING] Verify auth
VERBOSE: [SEND-HPOVREQUEST] BEGIN
VERBOSE: [SEND-HPOVREQUEST] Called from: Get-HPOVRemoteSupportSetting
VERBOSE: [SEND-HPOVREQUEST] Bound PS Parameters:
Key      Value
---      -----
uri      /rest/support/server-hardware/31333735-3232-4753-4831-3337584A4645
Hostname HPONEVIEWSERVERNAME


VERBOSE: [SEND-HPOVREQUEST] Process
VERBOSE: [SEND-HPOVREQUEST] Hostname value:
Name                              ConnectionId
----                              ------------
HPONEVIEWSERVERNAME            1


VERBOSE: [SEND-HPOVREQUEST] Filtering for Connection Object via PSObject:
Name                              ConnectionId
----                              ------------
HPONEVIEWSERVERNAME            1


VERBOSE: [SEND-HPOVREQUEST] Processing 'HPONEVIEWSERVERNAME' appliance connection request. 1 of 1
VERBOSE: [SEND-HPOVREQUEST] Requested URI '/rest/support/server-hardware/31333735-3232-4753-4831-3337584A4645' to 'HPONEVIEWSERVERNAME'
VERBOSE: [RESTCLIENT] Building new [System.Net.HttpWebRequest] object for GET
https://HPONEVIEWSERVERNAME/rest/support/server-hardware/31333735-3232-4753-4831-3337584A4645
VERBOSE: [SEND-HPOVREQUEST] Request: GET https://HPONEVIEWSERVERNAME/rest/support/server-hardware/31333735-3232-4753-4831-3337584A4645
VERBOSE: [SEND-HPOVREQUEST] Request Header 1: User-Agent = HPEOneview_PowerShell/4.10 (Microsoft Windows NT 10.0.14393.0)
VERBOSE: [SEND-HPOVREQUEST] Request Header 2: Content-Type = application/json
VERBOSE: [SEND-HPOVREQUEST] Request Header 3: Accept = application/json, text/html, application/xhtml+xml
VERBOSE: [SEND-HPOVREQUEST] Request Header 4: X-API-Version = 800
VERBOSE: [SEND-HPOVREQUEST] Request Header 5: accept-language = en_US
VERBOSE: [SEND-HPOVREQUEST] Request Header 6: accept-encoding = gzip, deflate
VERBOSE: [SEND-HPOVREQUEST] Request Header 7: auth = [*****REDACTED******]
VERBOSE: [SEND-HPOVREQUEST] Net.WebException Error caught
VERBOSE: [SEND-HPOVREQUEST] Exception Object:

PSMessageDetails      :
Exception             : System.Net.WebException: The remote server returned an error: (400) Bad Request.
                           at System.Net.HttpWebRequest.GetResponse()
                           at CallSite.Target(Closure , CallSite , WebRequest )
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], WebException
FullyQualifiedErrorId : WebException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Send-HPOVRequest<Process>, C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1821.1567\HPOneView.410.psm1: line 4861
                        at Get-HPOVRemoteSupportSetting<Process>, C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1821.1567\HPOneView.410.psm1:
                        line 18561
                        at Get-HPOVServer<Process>, C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1821.1567\HPOneView.410.psm1: line 31506
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}



VERBOSE: [SEND-HPOVREQUEST] Exception Message: The remote server returned an error: (400) Bad Request.
VERBOSE: [SEND-HPOVREQUEST] InnerException FullyQualifiedErrorId:
VERBOSE: [SEND-HPOVREQUEST] InnerException Message:
VERBOSE: [SEND-HPOVREQUEST] Exception
VERBOSE: [SEND-HPOVREQUEST] Getting Error Response
VERBOSE: [SEND-HPOVREQUEST] ERROR RESPONSE: {"errorCode":"DEVICE_NOT_ELIGIBLE","message":"Servername" is not eligible for remote
support.","details":"","recommendedActions":["The device must be eligible."],"errorSource":null,"nestedErrors":[],"data":{}}
VERBOSE: [SEND-HPOVREQUEST] Response Status: HTTP 400 [Bad Request]
VERBOSE: [SEND-HPOVREQUEST] Response Header: Connection =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Transfer-Encoding =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Cache-Control =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Content-Type =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Date =
VERBOSE: [SEND-HPOVREQUEST] Response Header: Server =
VERBOSE: [SEND-HPOVREQUEST] HTTP 400 error caught.
VERBOSE: [SEND-HPOVREQUEST] Cleaning up HttpWebRequest
Get-HPOVRemoteSupportSetting : The term 'HPOneView.Appliance.RemoteSupportResourceException' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:38
+ ... POVServer -Name "servername" | Get-HPOVRemoteSupportSetting -Verbose
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HPOneView.Appli...sourceException:String) [Get-HPOVRemoteSupportSetting], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException,Get-HPOVRemoteSupportSetting

# 2. Get-HPOVServer -Name Servername | Get-HPOVRemoteSupportSetting

### Version Information
ApplianceVersion: 4.10.01.348545.00 4.10.1821.1567 C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1821.1567

ApplianceVersion: 4.10.01.348545.00 4.10.1821.1567 C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1821.1567

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.14393.2515
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2515
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by ChrisLynchHPE** [comment]
Do you by chance have multiple major versions of the PowerShell library on your PC, and are you loading then unloading them within the same console?  Can you also please verify that the `HPOneView.410_Classes.dll` is this version:

```PowerShell

[PS] C:\Users\chris> (gci "C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\lib\HPOneView_Classes.410.dll").VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
4.10.1821.1567   4.10.1821.1567   C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\lib\HPOneView_Classes.410.dll

```

**Comment by sbkurid** [comment]
Do you by chance have multiple major versions of the PowerShell library on your PC, and are you loading then unloading them within the same console? - No

And Yes HPOneView.410_Classes.dll is the same version

PS C:\Users\kmg.acn.admin\Desktop> (gci "C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1821.1567\lib\HPOneView_Classes.410.dll").VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
4.10.1821.1567   4.10.1821.1567   C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1821.1567\lib\HPOneView_Classes.410.dll

**Comment by ChrisLynchHPE** [comment]
I found the issue, and will have it fixed in the next library update.

**Comment by sbkurid** [comment]
Thanks for the update and please let me know when the next library will be getting released.

**Comment by sbkurid** [comment]
Still the same error but identified the where the issue is.

The error is occurred only for Gen7 and below servers which is connected to HPOneView 4.1

**Comment by leearcher** [comment]
Have you tried the latest version?  I had a similar issue with G7 servers and remote support.

**Comment by ChrisLynchHPE** [comment]
@sbkurid it would certainly help to see logs from the Cmdlet call.  I had fixed this in the latest 4.10 library release.

**Comment by leearcher** [comment]
I've just tried this again and it seems to have an issue when it gets to the G7.  It used to work without any issues with the previous version.

Cannot find an overload for "WriteError" and the argument count: "0".
At C:\Program Files\WindowsPowerShell\Modules\HPOneView.410\4.10.1954.1523\HPOneView.410.psm1:25576 char:5
+                 $PSCmdlet.WriteError()
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

**Comment by ChrisLynchHPE** [comment]
Appologies, I don't have an unsupported platform to perform regression tests for this use case.

**Comment by ChrisLynchHPE** [comment]
This issue was addressed in prior 4.10 and 4.20 libraries releases.  However, as they are longer supported, the following current releases have this fix:

* [5.50.2680.1687](https://www.powershellgallery.com/packages/HPEOneView.550/5.50.2680.1687) 
* [5.40.2681.1725](https://www.powershellgallery.com/packages/HPEOneView.540/5.40.2681.1725)
* [5.30.2682.3811](https://www.powershellgallery.com/packages/HPEOneView.530/5.30.2682.3811)
* [5.20.2684.2161](https://www.powershellgallery.com/packages/HPOneView.520/5.20.2684.2161)
* [5.00.2685.1865](https://www.powershellgallery.com/packages/HPOneView.500/5.0.2685.1865)

Closing due to no further activity.  If you feel this is in error, please feel free to re-open this issue.
